article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard,name="dashboard"),
    path('addarticle/', views.addArticle,name="addarticle"),
    path('article/<int:id>', views.articleDetail,name="articledetail"),
    path('edit/<int:id>', views.editArticle,name="editarticle"),
    path('delete/<int:id>', views.deleteArticle,name="deletearticle"),
    path('deleteconfirm/<int:id>', views.deleteConfirm,name="deleteconfirm"),
    path('', views.showArticles,name="showarticles"),
    path('addcomment/<int:id>', views.addComment,name="addcomment"),
]

gblog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/',views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register,name="register"),
    path('login/', views.login,name="login"),
    path('logout/', views.logout,name="logout"),
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
        <a class="navbar-brand" href="{% url 'index' %}">G#23.Py.Dev</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about' %}">Kimdir?</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'article:showarticles' %}">Yazılar</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
             {% if request.user.is_authenticated %}
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli ( {{request.user.username}} )</a>
             </li>
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
             </li>
             {% else %}
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
              </li>
             {% endif %} 
             <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:register' %}">Kayıt Olun</a>
              </li>
              
             
              
            
              

          </ul>
        </div>
</nav>