article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard,name="dashboard"),
    path('addarticle/', views.addArticle,name="addarticle"),
    path('article/<int:id>', views.articleDetail,name="articledetail"),
    path('edit/<int:id>', views.editArticle,name="editarticle"),
    path('delete/<int:id>', views.deleteArticle,name="deletearticle"),
    path('deleteconfirm/<int:id>', views.deleteConfirm,name="deleteconfirm"),
    path('', views.showArticles,name="showarticles"),
    path('addcomment/<int:id>', views.addComment,name="addcomment"),
]

gblog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/',views.about,name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register,name="register"),
    path('login/', views.login,name="login"),
    path('logout/', views.logout,name="logout"),
]

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Gökalp Öztürk</h3>
<hr>
<p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sagittis lectus tristique mauris lacinia, eget sagittis nisi vulputate. Aliquam euismod eros eget vehicula tristique. Sed quis arcu ex. Vestibulum eget ullamcorper diam, eu euismod ante. Phasellus porta enim ac diam maximus, id viverra erat sagittis. Etiam quis tincidunt leo. Phasellus a nisi eros. Nullam varius velit in vulputate lobortis. Cras rhoncus placerat lectus at cursus. Donec odio urna, placerat at enim quis, scelerisque vestibulum lacus. Donec auctor a mauris quis convallis.
</p>
<p>
        Praesent pellentesque libero eget libero sagittis, et porta diam volutpat. In aliquet pulvinar accumsan. Nunc at porttitor urna, a malesuada elit. Ut leo leo, facilisis at ultrices ac, rutrum at dui. Morbi malesuada id nisl vitae ultricies. Sed eu viverra enim. Nam in volutpat est, ac convallis arcu. Vestibulum interdum, turpis non tempus laoreet, risus magna sodales orci, non finibus sem erat eu tellus.
</p>
<hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Yazı Ekle</h3>
            <hr>
            <form method="post" enctype="multipart/form-data" class="form-group">
                    {% csrf_token %}
                    {{form.media}}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary">Yazı Ekle</button>
            </form>
        </div>
</div>

{% endblock body %}

templates/articledetail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h2 class="mt-4">{{article.title}}</h2>

      <!-- Author -->
      <p class="lead">
        {{article.author.username}} tarafından yazıldı.
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
      {% endif %}
      

      <hr>

      <!-- Post Content -->
      <p>
          {{article.content|safe}}
      </p>

      <hr>
      <div class="card my-4">
          <h5 class="card-header">Yorum ekleyin:</h5>
          <div class="card-body">
            <form action="{% url 'article:addcomment' article.id %}" method="POST" >
              {% csrf_token %}
              <div class="form-group">
                  <label>İsim:</label>
                  <input name="comment_author" type="text" class="form-control" placeholder="İsminizi giriniz...">
                </div>
              <div class="form-group">
                  <label>Yorum:</label>
                <textarea name="comment_content" class="form-control" placeholder="Yorumunuzu giriniz..." rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Gönder</button>
            </form>
          </div>
        </div>
        {% if comments %}
        {% for item in comments %}
        <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h6 class="mt-0">{{item.comment_author}}:</h6>
              {{item.comment_content}} <br>
              <small>{{item.comment_date}} tarihinde yazıldı.</small>
            </div>
          </div>
          <hr>
        {% endfor %}
        {% else %}
        <div class="alert alert-danger">
          Bu makaleye ait yorum bulunmuyor...

        </div>
        {% endif %}
        

    </div>

  </div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <strong>{{request.user.username}}</strong>
</p>
<hr>
<a href="{% url 'article:addarticle' %}" class="btn btn-primary">Yazı Ekle</a>
<hr>
{% if articles  %}
<table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Tarih</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for item in articles  %}
           <tr>
                <th scope="row">{{item.id}}</th>
                <td><a href="{% url 'article:articledetail' item.id %}">{{item.title}}</a></td>
                <td>{{item.created_date}}</td>
                <td><a href="{% url 'article:editarticle' item.id %}" class="btn btn-primary btn-sm">Güncelle <i class="fa fa-pencil"></i></a></td>
                <td><a href="{% url 'article:deleteconfirm' item.id %}" class="btn btn-danger btn-sm">Sil <i class="fa fa-trash"></i></a></td>
           </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Veritabanında yazınız bulunmuyor...</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
{% endblock body %}

templates/deleteconfirm.html
{% extends "layout.html" %}

{% block body %}
<h4>{{article.title}} başlıklı yazıyı silmek istediğinize emin misiniz ?</h4>
<a href="{% url 'article:deletearticle' article.id %}" class="btn btn-danger btn-lg">Evet</a>
<a href="{% url 'article:dashboard' %}" class="btn btn-success btn-lg">Hayır</a>
{% endblock body %}

templates/editarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Yazı Güncelle</h3>
            <hr>
            <form method="post" enctype="multipart/form-data" class="form-group">
                    {% csrf_token %}
                    {{form.media}}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary">Yazıyı Güncelle</button>
            </form>
        </div>
</div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="jumbotron text-center">
<h2> <i>Gökalp Py.Dev Blog</i> </h2>
<p>Python dünyası üzerine paylaşımlar | print("Masaüstü, Web, Makine Öğrenmesi, Büyük Veri...") </p>
</div>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <title></title>
</head>
<body>
    {% include "includes/navbar.html" %}
    <div style="margin-top : 100px;" class="container">
        {% if messages %}
            
                {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                </div>
                {% endif %}
                {% endfor %}
            
        {% endif %}
        {% block body %}
        
        {% endblock body %}
    </div>
    <br><br><br>
    

    
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
</body>
<footer class="py-5 bg-primary">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Py.Dev 2018</p>
    </div>
</footer>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
        <div class="col-md-6 offset-md-3">
                <h3>Giriş Sayfası</h3>
                <hr>
                <form method="post" class="form-group">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary">Giriş Yap</button>
                </form>
        </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
        <div class="col-md-6 offset-md-3">
                <h3>Kayıt Sayfası</h3>
                <hr>
                <form method="post" class="form-group">
                    {% csrf_token %}
                    {{form|crispy}}
                     <button type="submit" class="btn btn-primary">Gönder</button>
                </form>
        </div>
</div>

{% endblock body %}

templates/showarticles.html
{% extends "layout.html" %}

{% block body %}
<h3>Yazılar</h3>
<hr>
{% if articles  %}
<form>
        {% csrf_token %}
    <div class="input-group stylish-input-group col-md-6">
        <input type="text" name="keyword" class="form-control" placeholder="Yazı Başlığı Arayın..." >
        <span class="input-group-addon">
            <button type="submit" class="btn btn-success">
                Başlık Ara
            </button>  
        </span>
    </div>
</form>

<hr>

  {% for article in articles  %}
    <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'article:articledetail' article.id %}"><h3 class="mt-4">{{article.title}}</h3></a>

      <!-- Author -->
      <p class="lead">
        {{article.author.username}} tarafından yazıldı.
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>

      <hr>

      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:articledetail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
      

      <hr>

      <!-- Post Content -->
      <p>
          {{article.content|safe|truncatewords:50}}
      </p>
      <a href="{% url 'article:articledetail' article.id %}" class="btn btn-primary btn-sm">Devamı için...</a>

      <hr>

    </div>

  </div>
  {% endfor %}
  {% if articles.has_other_pages %}
  <ul class="pagination">
    {% if articles.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">Önceki</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1"><span>Önceki</span></a></li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="page-item active"> <a class="page-link" href="#"> <span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ articles.next_page_number }}">Sonraki</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1"><span>Sonraki</span></a></li>
    {% endif %}
  </ul>
{% endif %}
{% else %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Yazı bulunmuyor...</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
{% endblock body %}